### ISSUE TITLE
not working on Ubuntu22.04 

### ISSUE THREAD

**Issue by wisrovi** [linkfy/TrollBananasPython#1]
The project is very interesting, I think I can do several things with it in a very entertaining way, but my operating system is Ubuntu 22.04, and there are some things that I can't get to work, it's a dll issue, I tried to fix it but the screen It doesn't come out transparent like your YouTube shorts

**Comment by linkfy** [comment]
This code is using Windows Api to be able to click through.
But I managed to get the transparent screen on Mac with 
```python
tk.wm_attributes("-transparent", True)
# Set window background color to transparent, another option
#tk.config(bg='systemTransparent')
canvas = Canvas(width=600, height=600)
canvas.config(bg='systemTransparent')
```
I suppose it will be very similar on Ubuntu.
The last thing to do will be to adapt the click_through function to use the Ubuntu window manager api  🙌

**Comment by wisrovi** [comment]
thanks
